name: Build Universal APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Webview Android App
        run: |
          npm install -g cordova
          cordova create myapp com.abhyas.myhtmlapp "My HTML App"
          cd myapp
          rm -rf www/*
          cp -r ../index.html www/
          cp -r ../style.css www/ 2>/dev/null || true
          cp -r ../script.js www/ 2>/dev/null || true
          cordova platform add android@12.0.1
          cordova build android --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Universal-App-APK
          path: myapp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
